"""create_shore_passes_table

Revision ID: 8f4a861acdd0
Revises: 0befe5cfff10
Create Date: 2026-02-10 12:28:55.133127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f4a861acdd0'
down_revision: Union[str, None] = '0befe5cfff10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shore_passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crew_profile_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=120), nullable=True),
    sa.Column('shore_pass_id', sa.String(length=64), nullable=False),
    sa.Column('out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crew_profile_id'], ['crew_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shore_pass_id')
    )
    op.create_index(op.f('ix_shore_passes_id'), 'shore_passes', ['id'], unique=False)
    op.drop_index('ix_file_assets_id', table_name='file_assets')
    op.drop_table('file_assets')
    op.drop_index('ix_password_resets_id', table_name='password_resets')
    op.drop_index('ix_password_resets_token', table_name='password_resets')
    op.drop_table('password_resets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='password_resets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='password_resets_pkey')
    )
    op.create_index('ix_password_resets_token', 'password_resets', ['token'], unique=False)
    op.create_index('ix_password_resets_id', 'password_resets', ['id'], unique=False)
    op.create_table('file_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='file_assets_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_assets_pkey')
    )
    op.create_index('ix_file_assets_id', 'file_assets', ['id'], unique=False)
    op.drop_index(op.f('ix_shore_passes_id'), table_name='shore_passes')
    op.drop_table('shore_passes')
    # ### end Alembic commands ###
